name: ci

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'feature-*'
      - 'release-*'
      - 'hotfix-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          -
            name: Checkout 
            uses: actions/checkout@v3
          - 
            name: Extract branch name
            shell: bash
            run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
            id: extract_branch
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Build and push
            uses: docker/build-push-action@v3
            with:
              context: ./
              file: ./Dockerfile
              builder: ${{ steps.buildx.outputs.name }}
              push: true
              tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sample-app:${{ github.sha }}, ${{ secrets.DOCKER_HUB_USERNAME }}/sample-app:${{ steps.extract_branch.outputs.branch }}
              cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/sample-app:buildcache
              cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/sample-app:buildcache,mode=max